spring:
  application:
    name: kafka-service
  kafka:
    bootstrap-servers: kafka:9092
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:9296

server:
  port: 9093

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://${EUREKA_HOST:localhost}:8761/eureka}
