spring:
  application:
    name: kafka-service
  kafka:
    bootstrap-servers: kafka:9092
  config:
    import: optional:configserver:http://config-server:9296

server:
  port: 9093

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://service-registry:8761/eureka}
