eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
management:
  tracing:
    sampling:
      probability: 1.0 # Enviar el 100% de las trazas
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # URL del endpoint de Zipkin
logging:
  level:
    '[io.micrometer.tracing]': DEBUG # Nivel de registro para trazas
    '[org.springframework]': INFO   # Nivel de registro para Spring
    '[org.springframework.cloud.config]': DEBUG
    '[org.springframework.web]': DEBUG
