server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-02439493.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oapqvhkafcaZpm4Z5d7
            client-secret: u9-DfB9zDGMAZnlynGCEvzlzAFe4qKiXO8fTSAE852jWyis6lxnR0-jqtXHBdwfL
        provider:
          okta:
            issuer-uri: https://dev-02439493.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

microservice:
  PRODUCT-SERVICE: http://PRODUCT-SERVICE/products/
  PAYMENT-SERVICE: http://PAYMENT-SERVICE/payments/
  ORDER-SERVICE: http://ORDER-SERVICE/orders/

logging:
  level:
    "[com.termiwum.orderservice.controller]": DEBUG
    "[com.termiwum.orderservice.service]": DEBUG
    "[com.termiwum.orderservice.external.decoder]": DEBUG
    "[com.termiwum.orderservice.external.intercept]": DEBUG
    "[org.springframework.security]": DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
